# -*- python -*-
import os

Import('env')

env.Append(LIBPATH=['#/lib'])
env.Append(LIBPATH=['$JLOCAL/lib'])
env.Append(LIBPATH=['/usr/X11R6/lib'])

# For Motif on FC6/7
env.Append(_LIBFLAGS=['-Wl,-R', '/opt/local/lib'])

# In order:
#  AMLIB (Atmospheric Mathmatical Library) calculations.
#  raf 'building blocks'.
#  File access stuff.
#  X windows/GUI.
#  General math libraries.
#  ADS3 real-time libraries.  Moved lower to 'if env.realtime'
env['LIBS'] = Split("""
  std user xlate
  hdr_api pms VarDB raf raf++
  ncaru netcdf pq
  Xm Xt X11
  gsl gslcblas m
""")

sources = Split("""
UDP_Base.cc
Xwin.c
adsIO.c
ads3IO.cc
amlibfn.c
async.c
average.c
calco.c
cb_defs.c
cb_edit.c
cb_main.c
cb_pause.c
circbuff.c
compute.c
config.cc
config_win.c
depend.c
despike.c
dq.c
error.c
filter.c
globals.cc
grnd_feed.cc
hdr_decode.c
hrloop.c
init.c
injectsd.cc
interp.c
log.c
logfile.c
lrloop.c
md5.cc
memalloc.cc
netcdf.c
nimbus.c
order.c
phase_shift.c
pms1d.c
popen.c
probe.c
psql.cc
brdcast.cc
rd_blanks.c
rd_ddor.c
rd_defs.c
rd_lag.c
rd_meta.c
rd_mod.c
rd_spike.c
rd_sum.c
rd_xmit.c
rec_decode.c
rtloop.c
search.c
setup.c
textfile.c
timeseg.c
""")

if int(env.realtime):
  env.Append(CPPPATH=[os.path.join(env['NIDAS_PATH'],'include')])
  sources = [sources, 'rtloop3.cc']
  env.Append(LIBS=['nidas', 'nidas_dynld', 'XmlRpcpp', 'xerces-c', 'bz2'])
  nlibpath = os.path.join(env['NIDAS_PATH'],'lib')
  env.Append(LIBPATH=[nlibpath])
  # This may be unnecessary and even undesirable with the introduction of
  # the ld.so.conf file.  However, leave it in for now, especially for the
  # case of building nimbus against the buildbot nidas.
  env.Append(_LIBFLAGS=['-Wl,-R', nlibpath])


nimbus = env.Program('nimbus', sources)

env.Install('$JLOCAL/bin', nimbus)

env.Default(nimbus)
