import sys

if (sys.platform in ['posix','linux', 'linux2']):
	SConscript('linux/SConscript')

if (sys.platform == 'darwin'):
	SConscript('mac/SConscript')

if (sys.platform == 'win32'):
    SConscript('bitrock/SConscript')

