import sys

if (sys.platform in ['posix','linux', 'linux2']):
    # Build a tar file distribution.
	SConscript('linux/SConscript')

if (sys.platform == 'darwin'):
    # Build the application disk image
    SConscript('mac/SConscript')
    # Package the disk image into a bitrock installer
    SConscript('bitrock/SConscript')

if (sys.platform == 'win32'):
    # Package the windows executable in a bitrock installer. 
    SConscript('bitrock/SConscript')

