/*
-------------------------------------------------------------------------
OBJECT NAME:	mtp.c

FULL NAME:	MTP

ENTRY POINTS:	scal()		Convert counts to brightness temperature

DESCRIPTION:	Derived calculations for the MTP.

COPYRIGHT:	University Corporation for Atmospheric Research, 2017
-------------------------------------------------------------------------
*/

#include "nimbus.h"
#include "amlib.h"

static const int NUM_CHANNELS = 3;     // number of frequencies used by the MTP
static const int NUM_SCAN_ANGLES = 10; // number of scan angles

// Set constants for platinum wire gain equation for temperature of target. 
// These should remain constant as long as physical target doesn't change.
// If target is replaced, these may change.
static float _AA = -244.3364635;
static float _Bb = 0.462418;
static float _cC = 0.0000588;
static float _DD = -0.000000013;
static float _Wtg = 0.1;

// the angle associated with the horizontal scan
static int _LocHor = 5;

// These are per-flight constants from the flights MTP .CAL file. They need
// to be read in per-flight from a cal file in
// $PROJ_DIR/<project>/<platform>/mtp, and eventually derived from the raw
// data and first principles. They are here for testing.
// These cals apply to DEEPWAVE RF01.
static float cnd0[3] = {86.926,76.711,80.198};
static float gof[3]  = {40.6,0.0,0.0};
static float gec1[3] = {19.87,23.10,26.05};
static float gec2[3] = {-0.1,-0.1,-0.1};

/* -------------------------------------------------------------------- */
/* The equations in this routine come from MTPGainEquation.docx (in svn) */
void scal(DERTBL *varp)
{  
  float Gnd[NUM_CHANNELS];
  float _Gain[NUM_CHANNELS];
  NR_TYPE scanbt[NUM_CHANNELS*NUM_SCAN_ANGLES];
  NR_TYPE scnt_inv[NUM_CHANNELS*NUM_SCAN_ANGLES];

  /* These 'GetSample()'s must match the same order as the variables
   * are listed in the DependTable.
   */
  NR_TYPE *scnt = GetVector(varp, 0);
  NR_TYPE *tcnt = GetVector(varp, 1);
  NR_TYPE  saat = GetSample(varp, 2);//Scan Avg Ambient Air Temp (OAT)
  NR_TYPE tr350cntp=GetSample(varp,3);//Platinum Multiplxr R350 Counts
  NR_TYPE tmixcntp=GetSample(varp,4);//Platinum Multiplxr Mixer Temperature Cnts
  NR_TYPE tr600cntp=GetSample(varp,5);//Platinum Multiplxr R600 Counts

  // Create a gain vector with all elements set to zero.
  for (size_t i=0; i<NUM_CHANNELS; i++) _Gain[i]=0.0;

  /* The scan counts are stored in the ads file as cnts[angle,channel], i.e.
   * {a1c1,a1c2,a1c3,a2c1,...}. Processing requires, and the final data are 
   * output as {c1a1,c1a2,c1a3,c1a4,...}. Invert the array here. (Note that this
   * will eventually be moved to a process function in 
   * nidas/src/nidas/dynld/raf. As of now, SCNT in the processed .nc file
   * is in the original matrix, but scanbt generated by this code is in the
   * inverted matrix, so they can't easily be compared.*/
  for (size_t j=0; j<NUM_SCAN_ANGLES; j++) {
      for (size_t i=0; i<NUM_CHANNELS; i++) {
         scnt_inv[i*10+j]=scnt[j*3+i];
      }
  }

  /* Create a Gnd vector */
  int TargIndx = 0;     // Index into tcnt for the target w/ ND on
  int TargNDIndx = 0;   // Index into tcnt for the target w/ ND off
  for (size_t i=0; i<NUM_CHANNELS; i++)
  {
      Gnd[i] = (tcnt[TargIndx]-tcnt[TargNDIndx])/cnd0[i];
      TargIndx = TargIndx+1;
      TargNDIndx = TargNDIndx+1;
  }

  // Counts for TMix
  float r = 350.0+(250.0*(tmixcntp-tr350cntp)/(tr600cntp-tr350cntp));

  // Temperature of the mixer (TMix, also known as Tifa)
  float TMix = _AA +_Bb*r + _cC*r*r + _DD*r*r*r;

  // g() is initialized to a value at the beginning of a flight and then is 
  // adjusted on a scan by scan basis in an iterative fashion. 
  for (size_t i=0; i<NUM_CHANNELS; i++)
  {
      if (_Gain[i] == 0.0) {
         // Initialize the gain
         _Gain[i] = (TMix-gof[0])*gec2[i] + gec1[i];
      } else {
         _Gain[i] = (_Gain[i] + Gnd[i] * _Wtg)/ (1+_Wtg);
      }
  }

  // Calculate Brightness Temperatures
  for (size_t i=0; i<NUM_CHANNELS;i++)
  {
      for (size_t j=0;j<NUM_SCAN_ANGLES;j++)
      {
         scanbt[i*10+j]=saat+(scnt_inv[i*10+j]-scnt_inv[i*10+_LocHor])/_Gain[i];
	 sprintf(buffer,"scanbt[%lu,%lu]=%f",i,j,scanbt[i*10+j]);
	 LogMessage(buffer);
      }
  }

  PutSample(varp, *scanbt);
}	/* END scal */

/* -------------------------------------------------------------------- */

/* END MTP.C */
