#!/bin/csh

foreach file ( a2d_cals hdr_api lib* vardb/lib hdrbld ncplot ncpp/src vardb/editor xhd xpms2d/src nimbus/src/qc instruments/mcr/display/src instruments/mcr/processor/src instruments/rdma ads_utils/edADShdr rtplot instruments/hvps/hvpsdiag instruments/usb2d/usb2diag ads/disc/src ads/dsm/src )
  (cd $file; echo $file; make clean)
end

cd nc_utils
foreach file ( asc2cdf n2asc ncReorder ncav ncextr ncmerge )
  (cd $file; echo $file; make clean)
end
cd ..

foreach file ( nimbus )
  (cd $file; echo $file; scons -c)
end


# Programs withOUT clean"" target.  WINDS requires xview toolkit.

foreach file ( winds/src )
  (cd $file; echo $file; rm *.o)
end
