#!/usr/bin/csh

\ping $argv[1] 3

if ($status == 1) then
        echo "Exiting...."
        sleep 3
        exit
endif
 
echo "Copying ${LOCAL}/winds/bin/w* to ${argv[1]}"

rcp -r mistral:${LOCAL}/dev/winds/bin/w* winds@${argv[1]}:${LOCAL}/winds/bin

echo "Done...Press return to exit."

$<
