# -*- python -*-

Import('env')

sources = Split("""
APN159.c
APN232.c
asas.c
async.c
avaps.c
climet.c
cmigit3.c
const.c
dme.c
dmt_hskp.c
etorq.c
event.c
fssp.c
gpsHw.c
gpsPps.c
gpsTans.c
hgm.c
irsHw.c
irsL51.c
loranc.c
ophir3.c
pms1_data.c
pms1_hskp.c
pms1_ps.c
pms2_data.c
pms2_hskp.c
psfd.c
rdma.c
serial.c
time.c
uvhyg.c
gpsGarmin.c
grey_hskp.c
tdl.c
float.c
AceAsia.c
""")

xlate = env.StaticLibrary('xlate' , sources)
env.Default(env.Install('#/lib/' , xlate)) 
