######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 23 09:58:13 2011
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DESTDIR = /opt/local/bin
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lnetcdf_c++ -lnetcdf -lhdf5 -lhdf5_hl

# Input
SOURCES += nc2iwg1.cc
