#! /usr/bin/python
#

import select
import socket
import sys

HOST = ''
PORT = 7071

#struct timeval tv; tv.tv_sec = 5; t.tv_usec = 0;

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind((HOST, PORT))

while True:
    r,w,e = select.select([s], [], [], 3)
    if r:
        packet = r[0].recv(1024)
        sys.stdout.write(packet)
