# -*- python -*-

import os
env = Environment(platform = 'posix',ENV= os.environ)
env['JLOCAL'] = os.environ['JLOCAL']

# Targets are only to install files.

Alias('install', env.Install('$JLOCAL/bin', 'vdbEditor'))

Alias('install', env.Install('$JLOCAL/lib/python/site-packages/vardb', ['addSignal.py',
	'delete.py', 'generateButtons.py', 'getInfo.py', 'makeSingleRadioButton.py',
	'newSignal.py', 'radioClickEvent.py', 'remove.py', 'setup.py', 'windowSetup.py']))
