/*
 * Resource file for hdrbld.
 */

static String fallback_resources[] =
  {
  /*
   * Some Generics
   */
  "*fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*XmForm.horizontalSpacing:		6",
  "*XmForm.verticalSpacing:		6",
  "*XmTextField.background:		Burlywood",
  "*XmTextField.foreground:		black",
  /*
   *	Defaults for First window to appear.
   */
  "*topLevelShell.allowShellResize:	True",
  "*topLevelShell.x:			100",
  "*topLevelShell.y:			100",
  "*topLevelShell.title:		Header Build",
  "*topLevelShell.iconName:		HdrBld",
  "*topLevelForm.bottomOffset:		6",

  "*menuBar*filePD_CB.labelString:	File",
  "*menuBar*filePD_CB.mnemonic:		F",
  "*menuBar*editPD_CB.labelString:	Edit",
  "*menuBar*editPD_CB.mnemonic:		E",
  "*menuBar*projFilePD_CB.labelString:	Proj Files",
  "*menuBar*projFilePD_CB.mnemonic:	P",
  "*menuBar*xferPD_CB.labelString:	Transfer(s)",
  "*menuBar*xferPD_CB.mnemonic:		T",

  "*menuBar*openNewFile.labelString:	Open New File",
  "*menuBar*openNewFile.mnemonic:	O",
  "*menuBar*openNewFile.accelerator:	Ctrl<Key>O",
  "*menuBar*openNewFile.acceleratorText:	Ctrl-O",
  "*menuBar*saveFile.labelString:	Save",
  "*menuBar*saveFile.mnemonic:		S",
  "*menuBar*saveFile.accelerator:	Ctrl<Key>S",
  "*menuBar*saveFile.acceleratorText:	Ctrl-S",
  "*menuBar*saveFileAs.labelString:	Save As",
  "*menuBar*saveFileAs.mnemonic:	A",
  "*menuBar*print.labelString:		Print",
  "*menuBar*print.mnemonic:		P",
  "*menuBar*print.accelerator:		Ctrl<Key>P",
  "*menuBar*print.acceleratorText:	Ctrl-P",
  "*menuBar*savequit.labelString:	Save & Exit",
  "*menuBar*quit.labelString:		Quit",
  "*menuBar*quit.mnemonic:		Q",
  "*menuBar*quit.accelerator:		Ctrl<Key>Q",
  "*menuBar*quit.acceleratorText:	Ctrl-Q",

  "*menuBar*search.labelString:		Find variable",
  "*menuBar*search.mnemonic:		F",
  "*menuBar*search.accelerator:		Ctrl<Key>F",
  "*menuBar*search.acceleratorText:	Ctrl-F",

  "*menuBar*editVarDB.labelString:	Variable Database",
  "*menuBar*editAsciiParms.labelString:	ASCII Serial Feed",
  "*menuBar*editDepend.labelString:	DependTable",
  "*menuBar*editDefaults.labelString:	Defaults",
  "*menuBar*editDespike.labelString:	Despike",
  "*menuBar*editLags.labelString:	Lags",
  "*menuBar*editPMS.labelString:	PMSspecs",
  "*menuBar*editBcastVars.labelString:	Broadcast Vars",

  "*menuBar*vinet.labelString:		netconfig (onboard)",
  "*menuBar*editRegions.labelString:	regions (onboard)",
  "*menuBar*editAC.labelString:		AircraftSpecs (onboard)",
  "*menuBar*editDSM.labelString:	dsmconfig (onboard)",

  "*menuBar*create.labelString:		Create/Init Project",
  "*menuBar*create.mnemonic:		C",
  "*menuBar*transOnboard.labelString:	Transfer Onboard",
  "*menuBar*transOnboard.mnemonic:	O",
  "*menuBar*transInhouse.labelString:	Transfer Inhouse",
  "*menuBar*transInhouse.mnemonic:	I",

  "*menuBar*xferADSrel.labelString:	ADS Release",
  "*menuBar*xferNIMrel.labelString:	Nimbus Release",
  "*menuBar*xferWINDSrel.labelString:	WINDS Release",
  "*menuBar*xferProjDefs.labelString:	hl proj/defaults",
  "*menuBar*xferLibs.labelString:	hl include & lib",
  "*menuBar*xfervxWorks.labelString:	vxWorks",
  "*menuBar*xferADSdev.labelString:	ADS Development",
  "*menuBar*xferNIMdev.labelString:	Nimbus Development",
  "*menuBar*xferWINDSdev.labelString:	WINDS dev binaries",

  "*acOpMenu.labelString:		Aircraft",

  "*hdrDump.labelString:		Header Dump",
  "*hdrDump.height:			32",
  "*hdrDump.width:			125",
  "*hdrDump.recomputeSize:		False",
  "*hdShell.title:			Header Dump",
  "*hdShell.x:				400",
  "*hdShell.y:				75",
  "*hdText.background:			Gray",
  "*hdText.columns:			85",
  "*hdText.editable:			False",
  "*hdText.editMode:			MULTI_LINE_EDIT",
  "*hdText.rows:			45",
  /*
   * Project Info Frame
   */
  "*projRC.orientation:			HORIZONTAL",
  "*projRC*fieldRC.orientation:		HORIZONTAL",
  "*projRC*projNumber.labelString:	Project Number",
  "*projRC*projName.labelString:	Project Name",
  "*projRC*projNumText.columns:		8",
  "*projRC*projNumText.maxLength:	8",
  "*projRC*projNameText.columns:	64",
  "*projRC*projNameText.maxLength:	64",
  /*
   * SDI variable Entry frame.
   */
  "*listFrame.shadowType:		SHADOW_OUT",
  "*listFrame.marginHeight:		5",
  "*listFrame.marginWidth:		5",
  "*sdiRC.orientation:			HORIZONTAL",
  "*sdiRC*varLabel.labelString:		Variable Name",
  "*sdiRC*varText.columns:		8",
  "*sdiRC*varText.maxLength:		7",
  "*opMenu0.labelString:		DSM",
  "*opMenu1.labelString:		Type",
  "*opMenu2.labelString:		SampleRate",
  "*opMenu3.labelString:		CardAddr",
  "*opMenu4.labelString:		Gain",
  "*opMenu5.labelString:		Offset",
  "*opMenu0.orientation:		VERTICAL",
  "*opMenu1.orientation:		VERTICAL",
  "*opMenu2.orientation:		VERTICAL",
  "*opMenu3.orientation:		VERTICAL",
  "*opMenu4.orientation:		VERTICAL",
  "*opMenu5.orientation:		VERTICAL",
  "*opMenuPD3*packing:			PACK_COLUMN",
  "*opMenuPD3*numColumns:		8",
  "*calRC*calLabel.labelString:		Calibrations",
  "*calRC*calText.columns:		14",
  "*calRC*calText.maxLength:		14",
  "*calRC.entryAlignment:		ALIGNMENT_CENTER",
  "*acceptButton.labelString:		Accept",
  "*acceptButton.height:		29",
  "*acceptButton.recomputeSize:		False",
  "*deleteButton.labelString:		Delete",
  "*deleteButton.height:		29",
  "*deleteButton.recomputeSize:		False",
  "*clearButton.labelString:		Clear",
  "*clearButton.height:			29",
  "*clearButton.recomputeSize:		False",
  /*
   * Scrolled List.
   */
  "*varList*background:			black",
  "*varList*foreground:			green",
  "*varList*listSizePolicy:		CONSTANT",
//  "*varList.selectionPolicy:		SINGLE_SELECT",
  "*varList*scrollBarDisplayPolicy:	STATIC",
  "*varList*visibleItemCount:		18",
  "*varList*width:			600",
  /*
   * Block Probes.
   */
  "*blockRB.orientation:		HORIZONTAL",
  "*blockRB.spacing:			35",
  "*navRC.orientation:			HORIZONTAL",
  "*navLabel0.labelString:		Primary Inertial",
  "*navLabel1.labelString:		Secondary Inertial",
  "*navLabel2.labelString:		Primary GPS",
  "*navLabel3.labelString:		Secondary GPS",
  "*navLabel4.labelString:		Secondary GPS",
  "*DSMmenu.labelString:		DSM",
  "*navRCsub.entryAlignment:		ALIGNMENT_CENTER",
  "*innerFrame.shadowType:		SHADOW_IN",

  "*pmsProbeRC.orientation:		HORIZONTAL",
  "*pmsFrames.shadowType:		SHADOW_IN",
  "*pmsIntOM.labelString:		Interface",
  "*pmsChanOM.labelString:		Channel",
  "*pmsResOM.labelString:		Resolution",

  "*otherProbeRC.orientation:		HORIZONTAL",
  "*otherFrames.shadowType:		SHADOW_IN",
  /*
   * Edit Project File Window
   */
  "*editShell.title:			Edit Project File",
  "*editShell.x:			200",
  "*editShell.y:			75",
  "*buttonFrame*XmPushButton.height:	32",
  "*buttonFrame*XmPushButton.width:	150",
  "*buttonFrame*XmPushButton.recomputeSize:	False",
  "*buttonFrame.shadowType:		SHADOW_IN",
  "*buttonRC.entryAlignment:		ALIGNMENT_CENTER",
  "*buttonRC.isAligned:			True",
  "*buttonRC.orientation:		HORIZONTAL",
  "*buttonRC.spacing:			75",
  "*saveButton.labelString:		Save",
  "*printButton.labelString:		Print",
  "*dismissButton.labelString:		Dismiss",
  "*projFileText.background:		Gray",
  "*projFileText.columns:		80",
  "*projFileText.editMode:		MULTI_LINE_EDIT",
  "*projFileText.rows:			35",
  /*
   * Dialog Boxes
   */
  "*errorBox*x:				200",
  "*errorBox*y:				200",
  "*errorBox*background:		DarkSlateGray",
  "*errorBox*dialogTitle:		Error Message",
  "*errorBox*foreground:		Red",
  "*errorBox*XmLabel.alignment:		ALIGNMENT_CENTER",
  "*queryBox*x:				200",
  "*queryBox*y:				200",
  "*queryBox*dialogTitle:		Need input",
  "*queryBox*XmLabel.alignment:		ALIGNMENT_CENTER",
  "*warnBox*x:				200",
  "*warnBox*y:				200",
  "*warnBox*background:			DarkSlateGray",
  "*warnBox*dialogTitle:		Warning Message",
  "*warnBox*foreground:			Yellow",
  "*warnBox*XmLabel.alignment:		ALIGNMENT_CENTER",
  "*fileBox.defaultPosition:		FALSE",
  "*fileBox.x:				130",
  "*fileBox.y:				200",
  "*fileBox*textColumns:		50",
  "*fileBox*dialogTitle:		Select a File",
  NULL
  };
