#!/bin/csh -x

cd ${PROJ_DIR}/$argv[1]

rsh $argv[2] mkdir ${PROJ_DIR}/$argv[1]/onboard

ftp -i -n << endftp
	open vivaldi.atd.ucar.edu
	user nimbus Pro#data
	cd /home/local/proj/$argv[1]/onboard
	bin
	mput *
	quit
endftp

echo "Onboard files have been copied to ${PROJ_DIR}/$argv[1]/onboard."
echo "Please copy the individual files manually to ${PROJ_DIR}/$argv[1]."
echo ""
echo "Type 'exit' when finished."
sleep 10
