# -*- python -*-

env = Environment(tools=['default', 'jlocal', 'vardb', 'netcdf'])

env.Append(CXXFLAGS=Split("-Wall -g -O2"))
env.Append(LIBS=["pms", "raf"])

vdb2ncml = env.Program("vdb2ncml.cc")

env.Default(vdb2ncml)
env.Install("$JLOCAL/bin", vdb2ncml)
