# -*- python -*-
##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

import sys
import os
import eol_scons

# Remove the previous svnInfo.h to insure that it is regenerated.
if os.access('#/svnInfo.h', os.W_OK):
    os.remove('#/svnInfo.h')
    
def RIC(env):
    # set the optimization/debuging
    env.Replace(CCFLAGS=['-g'])	
    # set attributes specific to the OS
    if sys.platform in ['posix','linux', 'linux2']:
        shared_libs = Split("""
           QtCore
           QtGui
           QtNetwork
           boost_program_options
		""")
    	env.AppendUnique(DEPLOY_SHARED_LIBS=shared_libs)
    	env['DEPLOY_DIRECTORY'] = env.Dir('#/installers/linux/RIC').get_abspath()

    elif env['PLATFORM'] == 'win32':
        # specializations for windows builds
        # Boost
        env['BOOST_LIBRARY_SUFFIX'] = '-mgw46-mt-1_42'
        env.AppendUnique(CPPPATH=[env['OPT_PREFIX']+'/include/boost-1_42'])
        # add compiler switch to disable the console window
        #env.AppendUnique(LINKFLAGS=['-Wl,-subsystem,windows']) 
         
    elif env['PLATFORM'] == 'darwin':
    	# Mac OSX setup
        # These flags cause the apps to be runnable on earlier versions of OSX.
        env.AppendUnique(CCFLAGS=['-mmacosx-version-min=10.6',])
        env.AppendUnique(LINKFLAGS=['-mmacosx-version-min=10.6',])
        # Boost libraries have an -mt suffix on OSX
    	env['BOOST_LIBRARY_SUFFIX'] = '-mt'

    return env

env = Environment(tools = ['default', 'svninfo', 'releaseid'], GLOBAL_TOOLS = ['prefixoptions', 'deploy', RIC])

# Create SVN info file. 
svnInfo = env.SvnInfo('#/svnInfo.h', '#')

SConscript("tools/SConscript")
SConscript("proxy/SConscript")
SConscript("switch/SConscript")
SConscript("installers/SConscript")

