.na
.nh
.TH NC_COMPARE 1 "29 March 2011" "Local Command"
.SH NAME
nc_compare \- netCDF compare utility
.SH SYNOPSIS
.B nc_compare primary_file secondary_file
.SH DESCRIPTION
.B nc_compare 
is a program for comparing two netCDF files.  Sample output:
.sp 1
Number of global attributes do not match, 32 vs. 38.
.br
Number of variables do not match, 97 vs. 98.
.sp 1
Gross errors; differences >= 1.0
.sp 1
                                 Mean
.br
Variable                 File1          File2     Diff
.br
PALT                8401.019186    8404.414730   3.395544
.br
PALTF              27562.398956   27573.539122  11.140165
.sp 1
Medium errors; differences >= 0.1 && < 1.0
.br
DPLC                 -49.506187     -49.402114   0.104074
.br
RHUM                  22.306021      22.462613   0.156593
.sp 1
Fine errors; differences > 0.00001 && < 0.1
.br
GGSPD                184.308466     184.308452   0.000014
.br
GGTRK                262.668736     262.668753   0.000017
.br
GGVEW                -67.326624     -67.326645   0.000020
.br
GGVNS                160.992438     160.992415   0.000023
.br
ATFR                 -34.112678     -34.112986   0.000308
.br
.PP
.SH BUGS
.PP
.SH AUTHOR
Chris Webster, National Center for Atmospheric Research
