# -*- python -*-
##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

import sys

#env = Environment(tools = ['default', 'qt4', 'logx'])

tools = Split("""
default qt4 logx
""")

env = Environment(tools = ['default']+tools)

#Import('env')
#env = env.Clone(tools = ['default', 'qt4', 'logx'])

qtmods = ['QtSvg', 'QtCore', 'QtGui', 'QtNetwork', 'QtSql', 'QtOpenGL']
env.EnableQt4Modules(qtmods)

env.AppendUnique(CPPPATH = ['/usr/local/include/QtCrypto'])
env.AppendUnique(LIBPATH = ['/usr/local/lib'])
env.AppendUnique(LIBS= ['qca'])

sources = ['main.cpp', 'switch.cpp', 'qsslserver.cpp']

switch= env.Program('switch',sources)

env.Default(switch)

env.AppendENVPath ('LD_LIBRARY_PATH', '/usr/local/lib')

