import sys

tools = Split("""
  default 
  boost
  boost_program_options
  ssl
  qtt_qtconfig
  doxygen
  ricutil
""")

env = Environment(tools = tools)

sources = Split("""
EmbeddedProxy.cpp
EmbeddedProxyServer.cpp
main.cpp
ProxyServer.cpp
Switch.cpp
SwitchConnection.cpp
SwitchMonitor.cpp
SwitchConfig.cpp
SslProxyServer.cpp
RateLimiter.cpp
""")

headers = Split("""
EmbeddedProxy.h
EmbeddedProxyServer.h
ProxyServer.h
Switch.h
SwitchConnection.h
SwitchMonitor.h
SwitchConfig.h
SslProxyServer.h
RateLimiter.h
Overview.h
""")

ric_switch = env.Program('ric_switch', sources)
env.Default(ric_switch)

env['DOXYFILE_DICT'].update({ "PROJECT_NAME" : "Switch" })
doxref = env.Apidocs(sources + headers)

SConscript("test/SConscript")


