import sys

tools = Split("""
  default 
  boost
  boost_program_options
  ssl
  qtt_qtconfig
  doxygen
  ricutil
""")

env = Environment(tools = tools)

sources = Split("""
EmbeddedProxy.cpp
EmbeddedProxyServer.cpp
main.cpp
ProxyServer.cpp
Switch.cpp
SwitchConnection.cpp
SwitchMonitor.cpp
SslProxyServer.cpp
""")

headers = Split("""
EmbeddedProxy.h
EmbeddedProxyServer.h
ProxyServer.h
Switch.h
SwitchConnection.h
SwitchMonitor.h
SslProxyServer.h
Overview.h
""")

ric_switch = env.Program('ric_switch', sources)
env.Default(ric_switch)

# Add switch to the Linux deploy target
if (sys.platform in ['posix','linux', 'linux2']):
    deploy = env.DeployProgram('ric_switch')
    env.Default(deploy)

env['DOXYFILE_DICT'].update({ "PROJECT_NAME" : "Switch" })
doxref = env.Apidocs(sources + headers)

SConscript("test/SConscript")


