#!/usr/bin/csh

\ping $argv[1] 3

if ($status == 1) then
        echo "Exiting...."
        sleep 3
        exit
endif
 
echo "Copying ${LOCAL}/proj/defaults to ${argv[1]}"

rcp -r mistral:${LOCAL}/proj/defaults ads@${argv[1]}:${LOCAL}/proj

echo "Done...Press return to exit."

$<
