#!/usr/bin/csh

\ping $argv[1] 3

if ($status == 1) then
        echo "Exiting...."
        sleep 3
        exit
endif
 
echo "Copying ${LOCAL}/dev/nimbus to ${argv[1]}"

rcp -r mistral:${LOCAL}/dev/nimbus/src/filter winds@${argv[1]}:${LOCAL}/nimbus/src
rcp -r mistral:${LOCAL}/dev/nimbus/include winds@${argv[1]}:${LOCAL}/nimbus
rcp -r mistral:${LOCAL}/dev/nimbus/src/amlib winds@${argv[1]}:${LOCAL}/nimbus/src
rcp -r mistral:${LOCAL}/dev/nimbus/lib winds@${argv[1]}:${LOCAL}/nimbus

echo "Done...Press return to exit."

$<
