import sys

# Run the bitrock install builder for specific architectures.

env = Environment(tools=['default', 'bitrock', 'osxdmg', 'svninfo'])

svnrevision = env['SVNREVISION']
svnrevision = svnrevision.replace(':','-')

# The bitrock recipe, which has logic that is based on the machine architecture.
bitrockxml = 'RICBitRock.xml'

if sys.platform == 'win32':
    installername = 'RIC-' + svnrevision + '.exe'
    sources = ['#/proxy/ric_proxy.exe']
    installer = env.BitRock(installername, bitrockxml, sources, svnrevision)
    Default(installer)
    
if sys.platform == 'darwin':
    installerdir = Dir('RIC-' + svnrevision + '.app')
    sources = Dir('#/installers/mac/RICProxy-' + svnrevision + '.app')
    installer = env.BitRock(installerdir, bitrockxml, [sources], svnrevision)
    # Create a disk image containing the installer.
    dmg = env.OsxDmg('RIC-' + svnrevision, installerdir)
    Default(dmg)
