tools = Split("""
  default 
  boost
  boost_program_options
  ssl
  qtt_qtconfig
  doxygen
""")

env = Environment(tools = tools)

sources = Split("""
EmbeddedProxy.cpp
EmbeddedProxyServer.cpp
main.cpp
ProxyServer.cpp
Switch.cpp
SwitchConnection.cpp
SslProxyServer.cpp
""")

headers = Split("""
EmbeddedProxy.h
EmbeddedProxyServer.h
ProxyServer.h
Switch.h
SwitchConnection.h
SslProxyServer.h
Overview.h
""")

switch = env.Program('switch', sources)
env.Default(switch)

env['DOXYFILE_DICT'].update({ "PROJECT_NAME" : "Switch" })
doxref = env.Apidocs(sources + headers)

SConscript("test/SConscript")


