######################################################################
# Automatically generated by qmake (1.04a) Tue Apr 8 18:49:19 2003
######################################################################

CONFIG += debug
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /jnet/shared/include

# Input
HEADERS += CanvasWindow.h DataPlot.h define.h extern.h
SOURCES += CanvasWindow.cc DataPlot.cc error.cc global.cc hvpsdiag.cc init.cc
LIBS += -L/jnet/linux/lib -lqwt -lraf++
