#!/bin/csh

# Script to run IDL CPI display GUI.

setenv IDL_STARTUP /tmp/cpi_idl_startup

cat > $IDL_STARTUP << EOF
device, retain=2, decom=0
!path=!path+':/opt/local/idl/lib/cpi'
EOF

chmod a+rw $IDL_STARTUP

idl -e cpidisplay

rm $IDL_STARTUP
