import sys

#env = Environment(tools = ['default', 'qt4', 'logx'])

tools = Split("""
default qt4
""")

env = Environment(tools = ['default']+tools)

qtmods = ['QtSvg', 'QtCore', 'QtGui', 'QtNetwork', 'QtSql', 'QtOpenGL']
env.EnableQt4Modules(qtmods)

if (env['PLATFORM'] != 'darwin'):
    # provided by the frameworks on darwin
    env.AppendUnique(LIBS= ['qca'])
    env.AppendUnique(CPPPATH = ['/usr/local/include/QtCrypto'])
    env.AppendUnique(LIBPATH = ['/usr/local/lib'])

serversources = ['servermain.cpp', 'sslserver.cpp', 'sslsocket.cpp']
sslserver = env.Program('sslserver', serversources)
env.Default(sslserver)

clientsources = ['clientmain.cpp', 'sslsocket.cpp']
sslclient = env.Program('sslclient', clientsources)
env.Default(sslclient)


