# -*- python -*-

Import('env')

##
##  Build xlate library
##
SConscript('xlate/SConscript')

##
##  Build std derived calculations
##
SConscript('std/SConscript')

##
##  Build user derived calculations
##
SConscript('user/SConscript')
