# -*- python -*-
##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

Import('env')

sources = Split("""
    CMIGITS3_Serial.cc
""")

env.Append(CPPPATH = '$PREFIX/include')

lib = env.SharedLibrary3('nidas_dynld_raf_CMIGITS3_Serial' , sources)

nodes = []
nodes += env.SharedLibrary3Install('$ARCHPREFIX',lib)

Alias('install',nodes)
Clean('install',nodes)
