#! /bin/sh
                                                                                
# /etc/init.d/httpd: start and stop the Apache httpd daemon
                                                                                
PATH=$PATH:/usr/bin
                                                                                
test -x /usr/bin/ACtracker.sh || exit 0
                                                                                
# Configurable options:
                                                                                
case "$1" in
  start)
        echo -n "Starting ACtracker.Sender"
        cd /tmp
        nohup /usr/bin/ACtracker.sh >> /tmp/ACtracker.out 2>&1 &
echo "."
        ;;
                                                                                
  *)
        echo "Usage: /etc/init.d/ACtracker start"
        exit 1
esac

exit 0
