/*
 * Resource file for xpms2d.
 */
 
static String fallback_resources[] =
  {
  "*defaultFontList:	-adobe-courier-bold-r-*-*-14-140-75-75-m-90-*-*",
  "*foreground:         black",

  "*font24:		-adobe-courier-bold-r-*-*-24-240-75-75-*-*-*-*",
  "*font18:		-adobe-courier-bold-r-*-*-18-180-75-75-*-*-*-*",
  "*font14:		-adobe-courier-bold-r-*-*-14-140-75-75-*-*-*-*",
  "*font12:		-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*font10:		-adobe-courier-bold-r-*-*-10-100-75-75-*-*-*-*",

  "*plRC*fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*controlRC*fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*printParmsRC*fontList:  -adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*editSpecShell*fontList: -adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",

  "*XmPushButton.height:		32",
  "*XmTextField.background:		Burlywood",
  "*XmTextField.foreground:		black",
  "*XmForm.horizontalSpacing:		4",
  "*XmForm.verticalSpacing:		4",
  "*canvasShell.title:			xpms2d 2.2.4",
  "*canvasShell.iconName:		xpms2d",
  "*canvasShell.allowShellResize:	True",
  "*canvasShell.x:			25",
  "*canvasShell.y:			250",
  "*controlShell.title:			Probe Selection",
  "*controlShell.x:			100",
  "*controlShell.y:			25",

  "*movieRC*XmScale.orientation:	HORIZONTAL",
  "*movieRC*timeScale.titleString:	Start            Time warp           Finish",
  "*movieRC*delayScale.titleString:	0          Frame delay (seconds)          4",
  "*movieRC*delayScale.decimalPoints:   3",
  "*movieRC*delayScale.maximum:         2000",
  "*movieRC*delayScale.scaleMultiple:   250",
  "*movieRC*delayScale.showValue:       True",

  "*pgButtRC.entryAlignment:            ALIGNMENT_CENTER",
  "*pgButtRC.orientation:               HORIZONTAL",
  "*pgButtRC.XmPushButton.recomputeSize:        False",
  "*movieRC*pgButtRC.XmPushButton.width:        75",

  "*movieRC*XmFrame.shadowType:		SHADOW_IN",
  "*movieRC*XmRowColumn.spacing:	0",
  "*probeRC*XmRowColumn.spacing:	0",
  "*cncRC*XmRadioBox.spacing:		0",
  "*denRC*XmRadioBox.spacing:		0",

  "*buttonFrame.shadowType:		SHADOW_IN",
  "*buttonRC.XmPushButton.recomputeSize:	False",
  "*buttonRC.XmPushButton.width:	125",
  "*buttonRC.entryAlignment:		ALIGNMENT_CENTER",
  "*buttonRC.isAligned:			True",
  "*buttonRC.orientation:		HORIZONTAL",

  "*drawForm.XmPushButton.recomputeSize:	False",
  "*drawForm.XmPushButton.width:	32",
  "*drawForm.XmPushButton.height:	32",

  "*canvas.background:			grey",
  "*canvas.height:			675",
  "*canvas.width:			1050",

  "*magShell.title:			Magnify Window",
  "*magShell.iconName:			2d Mag",
  "*magShell.allowShellResize:		True",
  "*magShell.x:				600",
  "*magShell.y:				25",

  "*magCanvas.background:		grey",
  "*magCanvas.height:			200",
  "*magCanvas.width:			400",

  "*pgButtRC.entryAlignment:		ALIGNMENT_CENTER",
  "*pgButtRC.XmPushButton.recomputeSize:	False",
  "*pgButtRC.XmPushButton.width:	100",

  "*pageFwd.labelString:		Page Fwd",
  "*pageBkd.labelString:		Page Bkd",

  "*headerShell.title:			netCDF Header",
  "*statsShell.title:			Data Set Statistics",
  "*specShell.title:			Spectrum",

  "*enchiladaShell.title:		Particle details",
  "*enchiladaText.background:		Gray",
  "*enchiladaText.columns:		80",
  "*enchiladaText.editable:		False",
  "*enchiladaText.editMode:		MULTI_LINE_EDIT",
  "*enchiladaText.fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*enchiladaText.rows:			42",

  "*hexShell.title:			Hex Output",
  "*hexText.background:			Gray",
  "*hexText.columns:			96",
  "*hexText.editable:			False",
  "*hexText.editMode:			MULTI_LINE_EDIT",
  "*hexText.fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*hexText.rows:			42",

  "*menuBar*newFile.labelString:	New Data File",
  "*menuBar*newFile.mnemonic:		N",
  "*menuBar*newFile.accelerator:	Ctrl<Key>N",
  "*menuBar*newFile.acceleratorText:	Ctrl-N",
  "*menuBar*addFile.labelString:	Add Data File",
  "*menuBar*addFile.mnemonic:		A",
  "*menuBar*readParms.labelString:	Read Parms File",
  "*menuBar*readParms.mnemonic:		R",
  "*menuBar*writeParms.labelString:	Write Parms File",
  "*menuBar*writeParms.mnemonic:	W",
  "*menuBar*printSetup.labelString:	Printer Setup",
  "*menuBar*savePS.labelString:		Save PostScript",
  "*menuBar*savePS.mnemonic:		S",
  "*menuBar*savePS.accelerator:		Ctrl<Key>S",
  "*menuBar*savePS.acceleratorText:	Ctrl-S",
  "*menuBar*print.labelString:		Print",
  "*menuBar*print.mnemonic:		P",
  "*menuBar*print.accelerator:		Ctrl<Key>P",
  "*menuBar*print.acceleratorText:	Ctrl-P",
  "*menuBar*savePNG.labelString:        Save PNG",
  "*menuBar*savePNG.mnemonic:           G",
  "*menuBar*quit.labelString:		Quit",
  "*menuBar*quit.mnemonic:		Q",
  "*menuBar*quit.accelerator:		Ctrl<Key>Q",
  "*menuBar*quit.acceleratorText:	Ctrl-Q",

  "*menuBar*viewHex.labelString:	View Hex",
  "*menuBar*viewHex.mnemonic:		X",
  "*menuBar*viewHex.accelerator:	Ctrl<Key>X",
  "*menuBar*viewHex.acceleratorText:	Ctrl-X",

  "*menuBar*viewData.labelString:	Normal",
  "*menuBar*viewDiag.labelString:	Diagnostic",
  "*menuBar*viewAll.labelString:	Whole Enchilada",
  "*menuBar*synthetic.labelString:	Toggle Synthetic Data",
  "*menuBar*wrapDisplay.labelString:	Toggle Display Wrap",
  "*menuBar*toggleTiming.labelString:	Toggle Timing Words",

  "*menuBar*editParms.labelString:	Time Series Parameters",
  "*menuBar*editParms.mnemonic:		P",
  "*menuBar*editParms.accelerator:	Ctrl<Key>E",
  "*menuBar*editParms.acceleratorText:	Ctrl-E",
  "*menuBar*editDiff.labelString:	Difference Parameters",
  "*menuBar*editDiff.mnemonic:		P",
  "*menuBar*editTrack.labelString:	XYZ Parameters",
  "*menuBar*editTrack.mnemonic:		T",
  "*menuBar*editSpec.labelString:	Spectral Parameters",
  "*menuBar*editSpec.mnemonic:		S",
  "*menuBar*editXYY.labelString:	XYY Parameters",
  "*menuBar*editXYY.mnemonic:		X",

  "*menuBar*viewASCII.labelString:	ASCII",
  "*menuBar*viewASCII.mnemonic:		A",
  "*menuBar*viewDiff.labelString:	Difference",
  "*menuBar*viewDiff.mnemonic:		D",
  "*menuBar*viewHeader.labelString:	netCDF Header",
  "*menuBar*viewHeader.mnemonic:	H",
  "*menuBar*viewStats.labelString:	Statistics",
  "*menuBar*viewStats.mnemonic:		S",
  "*menuBar*viewSpectra.labelString:	Spectrum",
  "*menuBar*viewCoSpectra.labelString:	Co-Spectrum",
  "*menuBar*viewQuadrature.labelString:	Quadrature",
  "*menuBar*viewCoherence.labelString:	Coherence",
  "*menuBar*viewPhase.labelString:	Phase",

  "*menuBar*autoScale.labelString:	Scale Y Axis",
  "*menuBar*autoScale.mnemonic:		A",
  "*menuBar*autoScale.accelerator:	Ctrl<Key>A",
  "*menuBar*autoScale.acceleratorText:	Ctrl-A",
  "*menuBar*clearPlot.labelString:	Clear current plot",
  "*menuBar*clearPlot.mnemonic:		C",
  "*menuBar*clearPlot.accelerator:	Ctrl<Key>C",
  "*menuBar*clearPlot.acceleratorText:	Ctrl-C",
  "*menuBar*unZoom.labelString:		Un-Zoom",
  "*menuBar*unZoom.mnemonic:		U",
  "*menuBar*unZoom.accelerator:		Ctrl<Key>U",
  "*menuBar*unZoom.acceleratorText:	Ctrl-U",
  /*
   * Edit Parms Window
   */
  "*plotParmsTitle.childHorizontalAlignment:	ALIGNMENT_CENTER",
  "*panelParmsTitle.childHorizontalAlignment:	ALIGNMENT_CENTER",
  "*plotParmsTitle.childVerticalAlignment:	ALIGNMENT_BASELINE_BOTTOM",
  "*panelParmsTitle.childVerticalAlignment:	ALIGNMENT_BASELINE_BOTTOM",
  "*plotParmsTitle.childHorizontalSpacing:	5",
  "*panelParmsTitle.childHorizontalSpacing:	5",
  "*plotParmsTitle.childType:		FRAME_TITLE_CHILD",
  "*panelParmsTitle.childType:		FRAME_TITLE_CHILD",
  "*plotParmsTitle.labelString:		Plot Parameters",
  "*panelParmsTitle.labelString:	Per Panel Parameters",
  /*
   * Control window
   */
  "*controlRC*XmFrame.XmLabel.childHorizontalAlignment: ALIGNMENT_CENTER",
  "*controlRC*XmFrame.XmLabel.childVerticalAlignment:   ALIGNMENT_BASELINE_BOTTOM",
  "*controlRC*XmFrame.XmLabel.childHorizontalSpacing:   5",
  "*controlRC*XmFrame.XmLabel.childType:                FRAME_TITLE_CHILD",

  "*controlRC.orientation:		HORIZONTAL",
  "*controlRC*XmFrame.shadowType:	SHADOW_IN",
//  "*controlRC*plRC*XmLabel.recomputeSize:	True",

  "*timeTitle.labelString:		Time Period",
  "*fileTitle.labelString:		Current File",
  "*probeTitle.labelString:		Probes",
  "*cncTitle.labelString:		Method",
  "*denTitle.labelString:		Density",

  "*conc0.labelString:			None",
  "*conc1.labelString:			Entire-in",
  "*conc2.labelString:			Center-in",
  "*conc3.labelString:			Reconstruct",

  "*plRC*XmLabel.alignment:		ALIGNMENT_END",
  "*plRC*XmLabel.recomputeSize:		False",
  "*plRC*XmLabel.width:			95",
  "*plRC.orientation:			HORIZONTAL",
  "*pnRC.orientation:			HORIZONTAL",
  "*plRC.marginHeight:			1",
  /*
   * Printer Setup Window
   */
  "*printShell.title:			Printer Setup",
  "*prOpMenu.labelString:		Printer",
  "*printParmsRC*lbl0.labelString:	Print command",
  "*printParmsRC*txt0.columns:		40",
  "*printParmsRC*txt0.maxLength:	40",
  "*printParmsRC*lbl1.labelString:	Plot Width",
  "*printParmsRC*txt1.columns:		10",
  "*printParmsRC*txt1.maxLength:	10",
  "*printParmsRC*lbl2.labelString:	Plot Height",
  "*printParmsRC*txt2.columns:		10",
  "*printParmsRC*txt2.maxLength:	10",
  /*
   * Edit Parameter Window
   */
  "*editParmsShell.title:		Edit Time Series Parameters",
  "*editParmsShell.x:			125",
  "*editParmsShell.y:			280",
  "*editDiffShell.title:		Edit Difference Parameters",
  "*editSpecShell.title:		Edit Spectral Parameters",
  "*editTrackShell.title:		Edit XYZ Parameters",
  "*editXYYShell.title:			Edit XYY Parameters",

  "*plRC*titleTxt.columns:		40",
  "*plRC*titleTxt.maxLength:		80",
  "*plRC*subTitleTxt.columns:		40",
  "*plRC*subTitleTxt.maxLength:		80",
  "*plRC*rtText.columns:		6",
  "*plRC*rtText.maxLength:		6",
  "*pnRC*timeText.columns:		8",
  "*pnRC*timeText.maxLength:		10",
  "*plRC*xLabel.labelString:		X label",
  "*plRC*yLabel0.labelString:		Y label (left)",
  "*plRC*yLabel1.labelString:		Y label (right)",
  "*plRC*zLabel.labelString:		Z label",
  "*plRC*labelTxt.columns:		40",
  "*plRC*labelTxt.maxLength:		40",
  "*plRC*xMin.labelString:		X min",
  "*plRC*xMax.labelString:		X max",
  "*plRC*yMin.labelString:		Y min",
  "*plRC*yMax.labelString:		Y max",
  "*plRC*zMin.labelString:		Z min",
  "*plRC*zMax.labelString:		Z max",
  "*plRC*xMax.width:			75",
  "*plRC*yMax.width:			75",
  "*plRC*zMax.width:			75",
  "*plRC*minMaxTxt.columns:		13",
  "*plRC*minMaxTxt.maxLength:		15",
  "*plRC*xTicMaj.labelString:		# X tics",
  "*plRC*yTicMaj.labelString:		# Y tics",
  "*plRC*zTicMaj.labelString:		# Z tics",
  "*plRC*xTicMin.labelString:		# minor",
  "*plRC*yTicMin.labelString:		# minor",
  "*plRC*zTicMin.labelString:		# minor",
  "*plRC*ticTxt.columns:		10",
  "*plRC*ticTxt.maxLength:		10",

  "*applyButton.labelString:		Apply",
  "*dismissButton.labelString:		Dismiss",
  "*printButton.labelString:		Print",
  "*resetButton.labelString:		Reset",
  "*saveButton.labelString:		Save",
  "*searchButton.labelString:		Search",
  "*searchTxt.columns:			12",
  "*searchTxt.maxLength:		32",
  "*parmsButton.labelString:		Edit Parms",
  /*
   *       Dialog Boxes
   */
  "*fileBox.defaultPosition:            FALSE",
  "*fileBox.x:                          300",
  "*fileBox.y:                          300",
  "*fileBox*textColumns:                50",
  "*fileBox*dialogTitle:                Select a File",
  "*errorBox.defaultPosition:           FALSE",
  "*errorBox.x:                         400",
  "*errorBox.y:                         400",
  "*errorBox*background:                DarkSlateGray",
  "*errorBox*dialogStyle:               DIALOG_FULL_APPLICATION_MODAL",
  "*errorBox*dialogTitle:               Error Message",
  "*errorBox*foreground:                Red",
  "*errorBox*XmLabel.alignment:         ALIGNMENT_CENTER",
  "*queryBox*dialogStyle:               DIALOG_FULL_APPLICATION_MODAL",
  "*queryBox*dialogTitle:               Need input",
  "*queryBox*alignment:                 ALIGNMENT_CENTER",
  "*warnBox.defaultPosition:            FALSE",
  "*warnBox.x:                          400",
  "*warnBox.y:                          400",
  "*warnBox*background:                 DarkSlateGray",
  "*warnBox*dialogStyle:		DIALOG_FULL_APPLICATION_MODAL",
  "*warnBox*dialogTitle:                Warning Message",
  "*warnBox*foreground:                 Yellow",
  "*warnBox*XmLabel.alignment:          ALIGNMENT_CENTER",
  NULL
  };

