/*
 * Resource file for edADShdr (ADS header editor)
 */

static String fallback_resources[] =
  {
  "*defaultFontList:	-adobe-courier-bold-r-*-*-14-140-75-75-*-*-*-*",
  "*XmForm.horizontalSpacing:			8",
  "*XmForm.verticalSpacing:			8",
  "*editFieldRC*XmLabel.width:			200",
  "*editFieldRC*XmLabel.recomputeSize:		False",
  "*buttonFrame*XmPushButton.height:		32",
  "*buttonFrame*XmPushButton.width:		100",
  "*buttonFrame*XmPushButton.recomputeSize:	False",
  "*XmTextField.background:			Burlywood",
  "*XmTextField.foreground:			black",
  "*buttonFrame.shadowType:			SHADOW_IN",
  "*buttonRC.entryAlignment:			ALIGNMENT_CENTER",
  "*buttonRC.isAligned:				True",
  "*buttonRC.orientation:			HORIZONTAL",

  "*topLevelShell.x:				200",
  "*topLevelShell.y:				200",
  "*topLevelShell.title:			Variable DataBase Editor",
  "*topLevelShell.iconName:			edADShdr",
  "*topLevelForm.resizePolicy:			RESIZE_GROW",

  "*menuBar*filePD_CB.labelString:		File",
  "*menuBar*filePD_CB.mnemonic:			F",
  "*menuBar*editPD_CB.labelString:		Edit",
  "*menuBar*editPD_CB.mnemonic:			E",

  "*menuBar*openNewFile.labelString:		Open New File",
  "*menuBar*openNewFile.mnemonic:		O",
  "*menuBar*openNewFile.accelerator:		Ctrl<Key>O",
  "*menuBar*openNewFile.acceleratorText:	Ctrl-O",
  "*menuBar*saveFile.labelString:		Save",
  "*menuBar*saveFile.mnemonic:			S",
  "*menuBar*saveFile.accelerator:		Ctrl<Key>S",
  "*menuBar*saveFile.acceleratorText:		Ctrl-S",
  "*menuBar*quit.labelString:			Quit",
  "*menuBar*quit.mnemonic:			Q",
  "*menuBar*quit.accelerator:			Ctrl<Key>Q",
  "*menuBar*quit.acceleratorText:		Ctrl-Q",

  "*menuBar*clearVar.labelString:		Clear Variable",
  "*menuBar*clearVar.mnemonic:			C",
  "*menuBar*clearVar.accelerator:		Ctrl<Key>C",
  "*menuBar*clearVar.acceleratorText:		Ctrl-C",
  "*menuBar*resetVar.labelString:		Reset Variable",
  "*menuBar*resetVar.mnemonic:			R",
  "*menuBar*resetVar.accelerator:		Ctrl<Key>R",
  "*menuBar*resetVar.acceleratorText:		Ctrl-R",
  "*menuBar*deleteVar.labelString:		Delete Variable",
  "*menuBar*deleteVar.mnemonic:			D",
  "*menuBar*deleteVar.accelerator:		Ctrl<Key>D",
  "*menuBar*deleteVar.acceleratorText:		Ctrl-D",

  "*acceptButton.labelString:			Accept",

  "*editFieldRC.orientation:			VERTICAL",
  "*editFieldRC.rowColumnType:			WORK_AREA",
  "*editFieldRC*XmForm.verticalSpacing:		0",
  "*editFieldRC*XmForm.horizontalSpacing:	3",
  "*editFieldRC*XmLabel.alignment:		ALIGNMENT_END",
  "*EFlabel0.labelString:			Project Number:",
  "*EFlabel1.labelString:			Flight Number:",
  "*EFlabel2.labelString:			Tape Number:",
  "*EFlabel3.labelString:			Flight Date:",
  "*EFlabel4.labelString:			Flight Time:",
  "*EFlabel5.labelString:			Aircraft:",
  "*EFtext0.columns:				8",
  "*EFtext0.maxLength:				8",
  "*EFtext1.columns:				8",
  "*EFtext1.maxLength:				8",
  "*EFtext2.columns:				8",
  "*EFtext2.maxLength:				8",
  "*EFtext3.columns:				12",
  "*EFtext3.maxLength:				12",
  "*EFtext4.columns:				12",
  "*EFtext4.maxLength:				12",
  "*EFtext5.columns:				8",
  "*EFtext5.maxLength:				8",

  "*errorBox*background:			DarkSlateGray",
  "*errorBox*dialogTitle:			Error Message",
  "*errorBox*foreground:			Red",
  "*errorBox*XmLabel.alignment:			ALIGNMENT_CENTER",
  "*warnBox*background:				DarkSlateGray",
  "*warnBox*dialogTitle:			Warning Message",
  "*warnBox*foreground:				Yellow",
  "*warnBox*XmLabel.alignment:			ALIGNMENT_CENTER",
  "*fileBox.defaultPosition:			FALSE",
  "*fileBox.x:					130",
  "*fileBox.y:					200",
  "*fileBox*textColumns:			50",
  "*fileBox*dialogTitle:			Select a File",
  NULL
  };
