from getInfo import getDictionary
sch=open('VDBSchema.xsd','w')
sch.write('<?xml version="1.0" encoding="UTF-8"?>\n')
sch.write('   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">\n')
sch.write('         <xs:element name="VarDB">\n')
sch.write('               <xs:complexType>\n')
sch.write('                     <xs:sequence>\n')
sch.write('                           <xs:element name="categories">\n')
sch.write('                                 <xs:complexType>\n')
sch.write('                                       <xs:sequence>\n')
sch.write('                                             <xs:element name="category" maxOccurs="unbounded">\n')
sch.write('                                                   <xs:complexType>\n')
sch.write('                                                         <xs:attribute name="name" type="xs:string"></xs:attribute>\n')
sch.write('                                                   </xs:complexType>\n')
sch.write('                                             </xs:element>\n')
sch.write('                                       </xs:sequence>')
sch.write('                                 </xs:complexType>\n')
sch.write('                           </xs:element>\n')
sch.write('                           <xs:element name="standard_names">\n')
sch.write('                                 <xs:complexType>\n')
sch.write('                                       <xs:sequence>\n')
sch.write('                                             <xs:element name="standard_name" maxOccurs="unbounded">\n')
sch.write('                                                   <xs:complexType>\n')
sch.write('                                                         <xs:attribute name="name" type="xs:string"></xs:attribute>\n')
sch.write('                                                   </xs:complexType>\n')
sch.write('                                             </xs:element>\n')
sch.write('                                       </xs:sequence>\n')
sch.write('                                 </xs:complexType>\n')
sch.write('                           </xs:element>\n')
sch.write('                           <xs:element name="variableCatalog">\n')
sch.write('                                 <xs:complexType>\n')
sch.write('                                       <xs:sequence>\n')
sch.write('                                             <xs:element name="variable" maxOccurs="unbounded">\n')
sch.write('                                                   <xs:complexType>\n')
sch.write('                                                         <xs:sequence>\n')

#get info iterations
for item in getDictionary('VDB.xml'):
   sch.write('                                                               <xs:element name="'+item+'" type="xs:string" minOccurs="0" ></xs:element>\n')

sch.write('                                                         </xs:sequence>\n')
sch.write('                                                         <xs:attribute name="name" type="xs:string"></xs:attribute>\n')
sch.write('                                                   </xs:complexType>\n')
sch.write('                                             </xs:element>\n')
sch.write('                                       </xs:sequence>\n')
sch.write('                                 </xs:complexType>\n')
sch.write('                           </xs:element>\n')
sch.write('                           <xs:element name="Dictionary">\n')
sch.write('                                 <xs:complexType>\n')
sch.write('                                       <xs:sequence>\n')
sch.write('                                             <xs:element name="definition" maxOccurs="unbounded" >\n')
sch.write('                                                 <xs:complexType>\n')
sch.write('                                                     <xs:simpleContent>\n')
sch.write('                                                         <xs:extension base="xs:string">\n')
sch.write('                                                             <xs:attribute name="name" type="xs:string"></xs:attribute>\n')
sch.write('                                                         </xs:extension>\n')
sch.write('                                                     </xs:simpleContent>\n')
sch.write('                                                 </xs:complexType>\n')
sch.write('                                             </xs:element>\n')
sch.write('                                       </xs:sequence>\n')
sch.write('                                 </xs:complexType>\n')
sch.write('                           </xs:element>\n')
sch.write('                     </xs:sequence>\n')
sch.write('               </xs:complexType>\n')
sch.write('         </xs:element>\n')
sch.write('   </xs:schema>\n')
sch.close()
