/*
 * Resource file for vared (VarDB editor)
 */

static String fallback_resources[] =
  {
  "*defaultFontList:	-adobe-courier-bold-r-*-*-14-140-75-75-*-*-*-*",
  "*XmForm.horizontalSpacing:			8",
  "*XmForm.verticalSpacing:			8",
  "*editFieldRC*XmLabel.width:			200",
  "*editFieldRC*XmLabel.recomputeSize:		False",
  "*buttonFrame*XmPushButton.height:		32",
  "*buttonFrame*XmPushButton.width:		100",
  "*buttonFrame*XmPushButton.recomputeSize:	False",
  "*XmTextField.background:			Burlywood",
  "*XmTextField.foreground:			black",
  "*buttonFrame.shadowType:			SHADOW_IN",
  "*buttonRC.entryAlignment:			ALIGNMENT_CENTER",
  "*buttonRC.isAligned:				True",
  "*buttonRC.orientation:			HORIZONTAL",

  "*topLevelShell.x:				200",
  "*topLevelShell.y:				200",
  "*topLevelShell.title:			Variable DataBase Editor",
  "*topLevelShell.iconName:			vared",
  "*topLevelForm.resizePolicy:			RESIZE_GROW",

  "*menuBar*filePD_CB.labelString:		File",
  "*menuBar*filePD_CB.mnemonic:			F",
  "*menuBar*editPD_CB.labelString:		Edit",
  "*menuBar*editPD_CB.mnemonic:			E",

  "*menuBar*openNewFile.labelString:		Open New File",
  "*menuBar*openNewFile.mnemonic:		O",
  "*menuBar*openNewFile.accelerator:		Ctrl<Key>O",
  "*menuBar*openNewFile.acceleratorText:	Ctrl-O",
  "*menuBar*saveFile.labelString:		Save",
  "*menuBar*saveFile.mnemonic:			S",
  "*menuBar*saveFile.accelerator:		Ctrl<Key>S",
  "*menuBar*saveFile.acceleratorText:		Ctrl-S",
  "*menuBar*saveFileAs.labelString:		Save As",
  "*menuBar*saveFileAs.mnemonic:		A",
  "*menuBar*saveFileAs.accelerator:		Ctrl<Key>A",
  "*menuBar*saveFileAs.acceleratorText:		Ctrl-A",
  "*menuBar*quit.labelString:			Quit",
  "*menuBar*quit.mnemonic:			Q",
  "*menuBar*quit.accelerator:			Ctrl<Key>Q",
  "*menuBar*quit.acceleratorText:		Ctrl-Q",

  "*menuBar*clearVar.labelString:		Clear Variable",
  "*menuBar*clearVar.mnemonic:			C",
  "*menuBar*clearVar.accelerator:		Ctrl<Key>C",
  "*menuBar*clearVar.acceleratorText:		Ctrl-C",
  "*menuBar*resetVar.labelString:		Reset Variable",
  "*menuBar*resetVar.mnemonic:			R",
  "*menuBar*resetVar.accelerator:		Ctrl<Key>R",
  "*menuBar*resetVar.acceleratorText:		Ctrl-R",
  "*menuBar*deleteVar.labelString:		Delete Variable",
  "*menuBar*deleteVar.mnemonic:			D",
  "*menuBar*deleteVar.accelerator:		Ctrl<Key>D",
  "*menuBar*deleteVar.acceleratorText:		Ctrl-D",

  "*acceptButton.labelString:			Accept",

  "*varList.background:				black",
  "*varList.foreground:				green",
  "*varList.listSizePolicy:			CONSTANT",
  "*varList.scrollBarDisplayPolicy:		STATIC",
  "*varList.visibleItemCount:			22",
  "*varList.width:				125",
  "*editFieldRC.orientation:			VERTICAL",
  "*editFieldRC.rowColumnType:			WORK_AREA",
  "*editFieldRC*XmForm.verticalSpacing:		0",
  "*editFieldRC*XmForm.horizontalSpacing:	3",
  "*editFieldRC*XmLabel.alignment:		ALIGNMENT_END",
  "*typeRadioBox.orientation:			HORIZONTAL",
  "*typeRadioBox.spacing:			20",
  "*fixedButton.labelString:			Fixed",
  "*floatButton.labelString:			Floating",
  "*EFlabel0.labelString:			Name:",
  "*EFlabel1.labelString:			Title:",
  "*EFlabel2.labelString:			Units:",
  "*EFlabel3.labelString:			Alt Units:",
  "*EFlabel4.labelString:			Range Type:",
  "*EFlabel5.labelString:			Fixed Range:",
  "*EFlabel6.labelString:			Floating Range:",
  "*EFlabel7.labelString:			Minimum Value:",
  "*EFlabel8.labelString:			Maximum Value:",
  "*EFlabel9.labelString:			Calibration Range:",
  "*catMenu.labelString:			Category:",
  "*catMenu*XmLabelGadget.alignment:		ALIGNMENT_END",
  "*stdNameMenu.labelString:			Standard Name:",
  "*stdNameMenu*XmLabelGadget.alignment:	ALIGNMENT_END",
  "*referenceButton.labelString:		Is this variable *the* reference?",
  "*EFtext0.columns:				16",
  "*EFtext0.maxLength:				16",
  "*EFtext1.columns:				35",
  "*EFtext1.maxLength:				64",
  "*EFtext2.columns:				16",
  "*EFtext2.maxLength:				16",
  "*EFtext3.columns:				16",
  "*EFtext3.maxLength:				16",
  "*EFtext4.columns:				16",
  "*EFtext4.maxLength:				16",
  "*EFtext5.columns:				16",
  "*EFtext5.maxLength:				16",
  "*EFtext6.columns:				16",
  "*EFtext6.maxLength:				16",
  "*EFtext7.columns:				16",
  "*EFtext7.maxLength:				16",
  "*EFtext8.columns:				16",
  "*EFtext8.maxLength:				16",
  "*EFtext9.columns:				16",
  "*EFtext9.maxLength:				16",
  "*EFtext10.columns:				16",
  "*EFtext10.maxLength:				16",

  "*errorBox*background:			DarkSlateGray",
  "*errorBox*dialogTitle:			Error Message",
  "*errorBox*foreground:			Red",
  "*errorBox*XmLabel.alignment:			ALIGNMENT_CENTER",
  "*warnBox*background:				DarkSlateGray",
  "*warnBox*dialogTitle:			Warning Message",
  "*warnBox*foreground:				Yellow",
  "*warnBox*XmLabel.alignment:			ALIGNMENT_CENTER",
  "*fileBox.defaultPosition:			FALSE",
  "*fileBox.x:					130",
  "*fileBox.y:					200",
  "*fileBox*textColumns:			50",
  "*fileBox*dialogTitle:			Select a File",
  NULL
  };
