######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 3 11:36:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . old ballard/BTI708
INCLUDEPATH += . old

# Input
HEADERS += snd_wx.h 
SOURCES += main.cc \
           snd_wx.cc 
