######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 7 18:19:29 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snd_udp.h
SOURCES += main.cc snd_udp.cc
