import sys

tools = Split("""
  protocol
""")

env = Environment(tools = ['default'] + tools)

sources = ['message.cpp', ]
test = env.Program('message', sources)
env.Default(test)

env = Environment(tools = ['default'] + tools)

symciphersources = ['symcipher.cpp', ]
symcipher = env.Program('symcipher', symciphersources)
env.Default(symcipher)
