import sys

tools = Split("""
  protocol
  evp
  doxygen
""")
env = Environment(tools = ['default'] + tools)

messagesources = ['message.cpp', ]
test = env.Program('message', messagesources)
env.Default(test)

tools = Split("""
  protocol
  evp
""")
env = Environment(tools = ['default'] + tools)

symciphersources = ['symcipher.cpp', ]
symcipher = env.Program('symcipher', symciphersources)
env.Default(symcipher)

tools = Split("""
  protocol
  evp
  qtt_qtconfig
""")
env = Environment(tools = ['default'] + tools)

instconfigsources = ['instconfig.cpp', ]
instconfig = env.Program('instconfig', instconfigsources)
env.Default(instconfig)

doxysources = ['message.cpp', 'symcipher.cpp', 'instconfig.cpp']

env['DOXYFILE_DICT'].update({ "PROJECT_NAME" : "protocol test" })
doxref = env.Apidocs(doxysources)

