/*
 * Resource file for rtplot.
 */

static String fallback_resources[] =
  {
  "*defaultFontList:    -adobe-courier-bold-r-*-*-14-140-75-75-m-90-*-*",

  "*font24:             -adobe-courier-bold-r-*-*-24-240-75-75-*-*-*-*",
  "*font18:             -adobe-courier-bold-r-*-*-18-180-75-75-*-*-*-*",
  "*font14:             -adobe-courier-bold-r-*-*-14-140-75-75-*-90-*-*",
  "*font12:             -adobe-courier-bold-r-*-*-12-120-75-75-*-70-*-*",
  "*font10:             -adobe-courier-bold-r-*-*-10-100-75-75-*-60-*-*",

  "*XmPushButton.height:			32",
  "*XmTextField.background:			Burlywood",
  "*XmTextField.foreground:			black",
  "*XmForm.horizontalSpacing:			4",
  "*XmForm.verticalSpacing:			4",
  "*canvasShell.title:				rtplot 2.0",
  "*canvasShell.iconName:			rtplot",
  "*buttonFrame.shadowType:			SHADOW_IN",
  "*buttonRC.XmPushButton.recomputeSize:	False",
  "*buttonRC.XmPushButton.width:		130",
  "*buttonRC.entryAlignment:			ALIGNMENT_CENTER",
  "*buttonRC.isAligned:				True",
  "*buttonRC.orientation:			HORIZONTAL",

  "*canvas.background:				grey",
  "*canvas.height:				500",
  "*canvas.width:				800",

  "*varList.background:				black",
  "*varList.foreground:				green",
  "*varList.scrollBarDisplayPolicy:		STATIC",
  "*varList.width:				100",

  "*pgButtRC.entryAlignment:			ALIGNMENT_CENTER",
  "*pgButtRC.orientation:			VERTICAL",
  "*freeze.labelString:				Freeze",

  "*editShell.title:				Edit Parameters",
  "*parmsForm.horizontalSpacing:		8",
  "*parmsForm.verticalSpacing:			8",
  "*parmsForm*buttonRC.spacing:			39",
  "*parmsRC*XmForm.horizontalSpacing:		5",
  "*parmsRC*XmLabel.alignment:			ALIGNMENT_END",
  "*parmsRC*XmLabel.recomputeSize:		False",
  "*parmsRC*XmLabel.height:			32",
  "*parmsRC*XmLabel.width:			120",
  "*menuBar*print.labelString:			Print",
  "*menuBar*print.mnemonic:			P",
  "*menuBar*print.accelerator:			Ctrl<Key>P",
  "*menuBar*print.acceleratorText:		Ctrl-P",
  "*menuBar*quit.labelString:			Quit",
  "*menuBar*quit.mnemonic:			Q",
  "*menuBar*quit.accelerator:			Ctrl<Key>Q",
  "*menuBar*quit.acceleratorText:		Ctrl-Q",
  "*menuBar*toggleCounts.labelString:		Toggle Counts",
  "*menuBar*toggleCounts.mnemonic:		C",
  "*menuBar*toggleCounts.accelerator:		Ctrl<Key>C",
  "*menuBar*toggleCounts.acceleratorText:	Ctrl-C",
  "*menuBar*toggleFlash.labelString:		Toggle Snapshot Mode",
  "*menuBar*toggleFlash.mnemonic:		F",
  "*menuBar*toggleFlash.accelerator:		Ctrl<Key>F",
  "*menuBar*toggleFlash.acceleratorText:	Ctrl-F",
  "*menuBar*autoScale.labelString:		Auto Scale Axies",
  "*menuBar*autoScale.mnemonic:			A",
  "*menuBar*autoScale.accelerator:		Ctrl<Key>A",
  "*menuBar*autoScale.acceleratorText:		Ctrl-A",
  "*menuBar*toggleGrid.labelString:		Toggle Grid",
  "*menuBar*toggleGrid.mnemonic:		G",
  "*menuBar*toggleGrid.accelerator:		Ctrl<Key>G",
  "*menuBar*toggleGrid.acceleratorText:		Ctrl-G",
  "*parmsRC*lbl0.labelString:			Title",
  "*parmsRC*txt0.columns:			40",
  "*parmsRC*txt0.maxLength:			40",
  "*parmsRC*lbl1.labelString:			Subtitle",
  "*parmsRC*txt1.columns:			40",
  "*parmsRC*txt1.maxLength:			40",
  "*parmsRC*lbl2.labelString:			X label",
  "*parmsRC*txt2.columns:			40",
  "*parmsRC*txt2.maxLength:			40",
  "*parmsRC*lbl3.labelString:			Y label",
  "*parmsRC*txt3.columns:			40",
  "*parmsRC*txt3.maxLength:			40",
  "*parmsRC*lbl4.labelString:			Start time",
  "*parmsRC*txt4.columns:			16",
  "*parmsRC*txt4.maxLength:			16",
  "*parmsRC*lbl5.labelString:			End Time",
  "*parmsRC*txt5.columns:			16",
  "*parmsRC*txt5.maxLength:			16",
  "*parmsRC*lbl6.labelString:			Y min",
  "*parmsRC*txt6.columns:			16",
  "*parmsRC*txt6.maxLength:			16",
  "*parmsRC*lbl7.labelString:			Y max",
  "*parmsRC*txt7.columns:			16",
  "*parmsRC*txt7.maxLength:			16",

  "*applyButton.labelString:			Apply",
  "*resetButton.labelString:			Reset",
  "*dismissButton.labelString:			Dismiss",
  /*
   *       Dialog Boxes
   */
  "*fileBox.defaultPosition:            FALSE",
  "*fileBox.x:                          130",
  "*fileBox.y:                          200",
  "*fileBox*textColumns:                50",
  "*fileBox*dialogTitle:                Select a File",
  "*errorBox.defaultPosition:           FALSE",
  "*errorBox.x:                         450",
  "*errorBox.y:                         100",
  "*errorBox*background:                DarkSlateGray",
  "*errorBox*dialogStyle:               DIALOG_FULL_APPLICATION_MODAL",
  "*errorBox*dialogTitle:               Error Message",
  "*errorBox*foreground:                Red",
  "*errorBox*XmLabel.alignment:         ALIGNMENT_CENTER",
  "*queryBox*dialogStyle:               DIALOG_FULL_APPLICATION_MODAL",
  "*queryBox*dialogTitle:               Need input",
  "*queryBox*alignment:                 ALIGNMENT_CENTER",
  "*warnBox.defaultPosition:            FALSE",
  "*warnBox.x:                          450",
  "*warnBox.y:                          100",
  "*warnBox*background:                 DarkSlateGray",
  "*warnBox*dialogStyle:                DIALOG_FULL_APPLICATION_MODAL",
  "*warnBox*dialogTitle:                Warning Message",
  "*warnBox*foreground:                 Yellow",
  "*warnBox*XmLabel.alignment:          ALIGNMENT_CENTER",
  NULL
  };
