#!/bin/csh

# Designed in PREDICT this script outputs 4 KML documents for ground
# based mission coordinater display.  Line items should be added to
# /net/www/docs/flight_data/##/GE/osm.kml to make available on menu.
# Also uses windbarb gif's we found.  Calls drop2kml which creates
# the windbarb placemark for each pressure.

mkdir -p /tmp/avaps
cd /tmp/avaps/
rm D*

set host=`hostname -s`

if $host == 'acserver' then
  echo 'Onboard'
  set inputdir='/mnt/r1/dropsondes/'
  set outputdir='/var/www/html/flight_data/GE/'
else
  echo 'Ground'
  set inputdir='/net/iftp/pub/incoming/predict/gv/'
  set outputdir='/net/www/docs/flight_data/GV/GE/'
endif

# Fetch latest D files.
/bin/cp ${inputdir}/D`date +%Y%m%d`* .
foreach file (D*.bz2)
  bunzip2 $file
end


foreach mbar (500 700 850 925)
  set out=${outputdir}/dwf${mbar}.kml
  echo '<?xml version="1.0" encoding="UTF-8"?>' > $out
  echo '<kml xmlns="http://www.opengis.net/kml/2.2">' >> $out
  echo '<Document>' >> $out
  echo ' <name>AVAPS ${mbar}mb winds</name>' >> $out

  echo '  <Style id="PM2">' >> $out
  echo '   <IconStyle>' >> $out
  echo '    <scale>0.5</scale>' >> $out
  echo '    <Icon>' >> $out
  echo '     <href>http:///flight_data/display/white.png</href>' >> $out
  echo '    </Icon>' >> $out
  echo '   </IconStyle>' >> $out
  echo '  </Style>' >> $out

  foreach file (D*)
    drop2kml ${mbar} < $file >> $out
  end

  echo '</Document>' >> $out
  echo '</kml>' >> $out
end
