#!/bin/sh 

# Get date and time, used to name new directory for images.
imageDirectory="/mnt/camera/FwdCam/`date +%y%m%d_%H%M%S`"

# Make directory and move into it. Run program from there.
mkdir -p -m a+rw $imageDirectory
echo " Images stored in $imageDirectory/" >> /mnt/camera/FwdCam/camera.log
cd $imageDirectory

# grabcolor program will quit if it doesn't see a camera, and
# camera isn't powered until weight on wheels switch is triggered
# since it gets it's power from 28V anti-ice.
# So, loop until it runs. Grabcolor gets images at its own rate. The
# sleep here is only between attempts to run grabcolor.
# I'm not sure what would happen with
# a touch and go where the camera momentarily loses power
# while the program is running. I think it would quit and then restart.

while : 
    do
    /home/ads/grabdma/grabcolor
    sleep 10
done

