#!/bin/csh -f
## client_call_WINDS
## Script to start WINDS on a Display computer.
## 7/12/04 Brandon Slaten
## 10/21/04 Midified for private Subnet BLS

# Hercules
set windsserver = hercules.display.c130

# echo $windsserver

ping -w 1 $windsserver 
if ($status) then 
#        echo Cannot ping $mcrtdserver, I give up. 
#        echo ''
       exit 
endif

/usr/bin/X11/xhost + 

#echo  request_winds for  `uname -n`
/usr/bin/rsh $windsserver request_winds `uname -n`
