tools = Split("""
  default 
  ssl
  protocol
""")

env = Environment(tools = ['default'] + tools)

serversources = ['servermain.cpp', 'Server.cpp', 'ServerConnection.cpp' ]
sslserver = env.Program('sslserver', serversources)
env.Default(sslserver)

clientsources = ['clientmain.cpp', ]
sslclient = env.Program('sslclient', clientsources)
env.Default(sslclient)


