tools = Split("""
  default 
  ssl
  protocol
  ricutil
""")

env = Environment(tools = ['default'] + tools)

serversources = ['servermain.cpp', 'Server.cpp',]
sslserver = env.Program('sslserver', serversources)
env.Default(sslserver)

clientsources = ['clientmain.cpp', ]
sslclient = env.Program('sslclient', clientsources)
env.Default(sslclient)

tools = Split("""
  default 
  evp
""")
env = Environment(tools = ['default'] + tools)

evpsources = ['evpmain.cpp', ]
evp = env.Program('evp', evpsources)
env.Default(evp)

evpsources = ['base64main.cpp', ]
base64 = env.Program('base64', evpsources)
env.Default(base64)

