# -*- python -*-

# Use the site_scons in the RAF source tree if it has not been checked
# out directly into this directory or specified with --site-dir.

import sys
import os
sys.path.append(os.path.abspath("../caledit/site_scons"))
import site_init

env = Environment (tools = ['default', 'doxygen', 'pylint', 'pytest'])

raf_python_files = env.FindPythonFiles('raf')
iss_python_files = env.FindPythonFiles('iss')
iss_python_files = [ipf for ipf in iss_python_files 
                    if str(ipf) not in ['iss/messaging/sounding.py']]
all_python_files = raf_python_files + iss_python_files

env.PythonLint('check', all_python_files)
env.PythonLint('rafcheck', raf_python_files)

# py.test -v -k -test_main_operations  iss/tests/.
# py.test -v -s iss/tests/. --quick=1 --dlog


test = env.Command("test", all_python_files, 'py.test --quick=1 ${SOURCES}')
env.Alias("test", test)
raftest = env.Command("raftest", raf_python_files, 'py.test --quick=1 ${SOURCES}')
env.Alias("raftest", raftest)

# raftest = env.Command("raftest", raf_python_files, 
#                       'py.test --quick=1 ${SOURCES}')
# isstest = env.Command("isstest", iss_python_files,
#                       'py.test --quick=1 ${SOURCES}')
# env.Alias("test", [raftest, isstest])

