#!/bin/csh

# Script to run IDL SID2 processing.  This will read raw SID2 files and write
# histogram and time series data similar to a PMS or OAP probe into the
# specified netCDF file.

if ( $#argv != 3 ) then
  echo Usage: procsid2h raw_data_directory -o netcdf_file.nc
  exit 1
endif

#idl -e "procsid2h, '$argv[1]'"
idl -e "\!path=\!path+':/opt/local/idl/lib' & procsid2h, '$argv[1]', pthfile='$argv[3]'"

