#!/bin/csh
#
# Launches nimbus for real-time aircraft mode.

setenv XMIT_DIR /tmp/xmit

# Make sure it exists.
/bin/mkdir -p $XMIT_DIR

# Expire any existing stuff (or is this done on the ground side???)
/home/local/bin/pqexpire -a 0.001 -i 0 -p "nimbus_sql"

# Remove any existing sql files.
set nonomatch
foreach file (${XMIT_DIR}/*sql*)
  /bin/rm $file
end

# Fire up nimbus in real-time with transmit on (-x to be replaced by
# standalone program).
nimbus -rt3 -x
