######################################################################
# Automatically generated by qmake (1.04a) Sun Jan 4 14:46:13 2004
######################################################################

QT += network
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += rd_udp.h
SOURCES += main.cc rd_udp.cc
