# -*- python -*-

env = Environment(tools=['default', 'jlocal', 'vardb', 'testing', 
                         'postgres_testdb'])
env.Append(CPPPATH='/usr/include/python2.7')
env.Append(LIBS='boost_python')

module = env.SharedLibrary(env.File('vardb/_vardb.so'), ['src/vardb.cc'])
pysrcs = Split("vardb/__init__.py")
tests = Split("vardb/test_vardb.py")

pg = env.PostgresTestDB()
sql = env.File("../../nagios-qc/winter-real-time.sql")

env.AppendENVPath('PYTHONPATH', "#/../python")

runtest = env.TestRun('pytests', tests+module+pysrcs+[sql],
                      [ pg.action_run_aircraftdb,
                        "py.test ${SOURCE}",
                        pg.action_stopdb ])

# Do not run these tests by default until the module is built by default.
#
# env.DefaultTest(runtest)
