# -*- python -*-

env = Environment()

# No RCS/SCCS checkout.
env.SourceCode('.', None)

make_amlib = env.Program('make_amlib', 'make_amlib.c')
amlibfn = env.Command('amlibfn.h', ['amlib.fns', make_amlib], "cd ../include; ./make_amlib")
env.Clean(amlibfn, ['xlatefns.h', 'amlibProto.h'])

svnInfo = env.Command('svnInfo.h', None, "cd ../include; ./makeSvnInfoHeaderFile.sh")

env.AlwaysBuild(svnInfo)
env.Precious(svnInfo)

env.Default([amlibfn, svnInfo])
