# -*- python -*-
import os

env = Environment()

make_amlib = env.Program('make_amlib', 'make_amlib.cc')
amlibfn = env.Command('amlibProto.h', ['amlib.fns', make_amlib], "cd include; ./make_amlib")
env.Clean(amlibfn, ['xlatefns.h', 'amlibProto.h'])

env.Default([amlibfn])
