
env = Environment(tools = ['default', 'qt4', 'logx'])

qtmods = ['QtSvg', 'QtCore', 'QtGui', 'QtNetwork', 'QtSql', 'QtOpenGL']
env.EnableQt4Modules(qtmods)

sources = ['main.cpp', 'senderreceiver.cpp', 'sslserver.cpp', 'qsslserver.cpp',
           'sslclient.cpp', 'sendudp.cpp', 'proxy.cpp', 'switch.cpp']

qtudp = env.Program('qtudp',sources)

env.Default(qtudp)