/*
 * Resource file for mcrtd.
 */

static String fallback_resources[] =
  {
  "*defaultFontList:	-adobe-courier-bold-r-*-*-14-140-75-75-m-90-*-*",

  "*font24:		-adobe-courier-bold-r-*-*-24-240-75-75-*-*-*-*",
  "*font18:		-adobe-courier-bold-r-*-*-18-180-75-75-*-*-*-*",
  "*font14:		-adobe-courier-bold-r-*-*-14-140-75-75-*-*-*-*",
  "*font12:		-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*font10:		-adobe-courier-bold-r-*-*-10-100-75-75-*-*-*-*",

  "*plRC*fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*varList*fontList:	-adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",
  "*editSpecShell*fontList: -adobe-courier-bold-r-*-*-12-120-75-75-*-*-*-*",

  "*XmPushButton.height:		32",
  "*XmTextField.background:		Burlywood",
  "*XmTextField.foreground:		black",
  "*XmForm.horizontalSpacing:		4",
  "*XmForm.verticalSpacing:		4",
  "*canvasShell.title:			MCR Display",
  "*canvasShell.iconName:		MCR",
  "*canvasShell.allowShellResize:	True",
  "*canvasShell.x:			25",
  "*canvasShell.y:			100",
  "*buttonFrame.shadowType:		SHADOW_IN",
  "*buttonRC.XmPushButton.recomputeSize:	False",
  "*buttonRC.XmPushButton.width:	125",
  "*buttonRC.entryAlignment:		ALIGNMENT_CENTER",
  "*buttonRC.isAligned:			True",
  "*buttonRC.orientation:		HORIZONTAL",

  "*drawForm.XmPushButton.recomputeSize:	False",
  "*drawForm.XmPushButton.width:	32",
  "*drawForm.XmPushButton.height:	32",

  "*canvas.background:			grey",
  "*canvas.height:			570",
  "*canvas.width:			1050",

  "*pgButtRC.entryAlignment:		ALIGNMENT_CENTER",
  "*pgButtRC.XmPushButton.recomputeSize:	False",
  "*pgButtRC.XmPushButton.width:	100",

  "*pageFwd.labelString:		Page Fwd",
  "*pageBkd.labelString:		Page Bkd",

  "*menuBar*newFile.labelString:	New Data File",
  "*menuBar*newFile.mnemonic:		N",
  "*menuBar*newFile.accelerator:	Ctrl<Key>N",
  "*menuBar*newFile.acceleratorText:	Ctrl-N",
  "*menuBar*addFile.labelString:	Add Data File",
  "*menuBar*addFile.mnemonic:		A",
  "*menuBar*readParms.labelString:	Read Parms File",
  "*menuBar*readParms.mnemonic:		R",
  "*menuBar*writeParms.labelString:	Write Parms File",
  "*menuBar*writeParms.mnemonic:	W",
  "*menuBar*printSetup.labelString:	Printer Setup",
  "*menuBar*savePS.labelString:		Save PostScript",
  "*menuBar*savePS.mnemonic:		S",
  "*menuBar*savePS.accelerator:		Ctrl<Key>S",
  "*menuBar*savePS.acceleratorText:	Ctrl-S",
  "*menuBar*print.labelString:		Print",
  "*menuBar*print.mnemonic:		P",
  "*menuBar*print.accelerator:		Ctrl<Key>P",
  "*menuBar*print.acceleratorText:	Ctrl-P",
  "*menuBar*quit.labelString:		Quit",
  "*menuBar*quit.mnemonic:		Q",
  "*menuBar*quit.accelerator:		Ctrl<Key>Q",
  "*menuBar*quit.acceleratorText:	Ctrl-Q",

  "*plRC*XmLabel.alignment:		ALIGNMENT_END",
  "*plRC*XmLabel.recomputeSize:		False",
  "*plRC*XmLabel.width:			95",
  "*plRC.orientation:			HORIZONTAL",
  "*pnRC.orientation:			HORIZONTAL",
  "*plRC.marginHeight:			1",
/*
 * Printer Setup Window
 */
  "*printShell.title:			Printer Setup",
  "*printParmsRC*lbl0.labelString:	Print command",
  "*endVolt.columns:			8",
  "*endVolt.maxLength:			8",
  "*printParmsRC*lbl1.labelString:	Plot Width",
  "*startVolt.columns:			8",
  "*startVolt.maxLength:		8",
  "*printParmsRC*lbl2.labelString:	Plot Height",
  "*printParmsRC*txt2.columns:		10",
  "*printParmsRC*txt2.maxLength:	10",

  "*applyButton.labelString:		Apply",
  "*dismissButton.labelString:		Dismiss",
  "*printButton.labelString:		Print",
  "*resetButton.labelString:		Reset",
  "*saveButton.labelString:		Save",
  "*parmsButton.labelString:		Edit Parms",
/*
 *       Dialog Boxes
 */
  "*fileBox.defaultPosition:		FALSE",
  "*fileBox.x:				130",
  "*fileBox.y:				200",
  "*fileBox*textColumns:		50",
  "*fileBox*dialogTitle:		Select a File",
  "*errorBox.defaultPosition:		FALSE",
  "*errorBox.x:				450",
  "*errorBox.y:				100",
  "*errorBox*background:		DarkSlateGray",
  "*errorBox*dialogStyle:		DIALOG_FULL_APPLICATION_MODAL",
  "*errorBox*dialogTitle:		Error Message",
  "*errorBox*foreground:		Red",
  "*errorBox*XmLabel.alignment:		ALIGNMENT_CENTER",
  "*queryBox*dialogStyle:		DIALOG_FULL_APPLICATION_MODAL",
  "*queryBox*dialogTitle:		Need input",
  "*queryBox*alignment:			ALIGNMENT_CENTER",
  "*warnBox.defaultPosition:		FALSE",
  "*warnBox.x:				450",
  "*warnBox.y:				100",
  "*warnBox*background:			DarkSlateGray",
  "*warnBox*dialogStyle:		DIALOG_FULL_APPLICATION_MODAL",
  "*warnBox*dialogTitle:		Warning Message",
  "*warnBox*foreground:			Yellow",
  "*warnBox*XmLabel.alignment:		ALIGNMENT_CENTER",
  NULL
  };

