# -*- python -*-
##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

import sys

tools = Split("""
default
evp
""")

env = Environment(tools = ['default']+tools)
if (sys.platform=='win32'):
    env.Append(LIBS=['gdi32'])

gensymkeysrcs = ['gensymkey.cc']
gensymkey = env.Program('gensymkey', gensymkeysrcs);
env.Default(gensymkey)
