#! /bin/sh
#
# Setup the environment to run within the installed directory tree, where
# the top of that tree is determined by this script.
#

mydir=`dirname $0`
prefix=$mydir/..

LD_LIBRARY_PATH="$prefix/lib"
export LD_LIBRARY_PATH
PATH="$prefix/bin:${PATH}"
export PATH
echo LD_LIBRARY_PATH set to $LD_LIBRARY_PATH
echo PATH set to $PATH

exec $prefix/bin/proxy $@
