######################################################################
# Automatically generated by qmake (1.04a) Tue Apr 8 18:49:19 2003
######################################################################

CONFIG += debug
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /opt/nidas/x86/include

# Input
HEADERS += CanvasWindow.h DataPlot.h
SOURCES += CanvasWindow.cc DataPlot.cc usb2d.cc
