# -*- python -*-

Import('env')

thisEnv = env.Clone(CC = 'gcc', CCFLAGS=[])

sources = Split("""
        conversion.c
        cray.c
        packf.c
""")

ncaru = thisEnv.StaticLibrary('ncaru' , sources)

def libncaru(env):
    env.Append(LIBS = ncaru)

Export('libncaru')
