tools = Split("""
  default 
  ssl
  protocol
  qtt_qtconfig
""")

env = Environment(tools = ['default'] + tools)

sources = Split("""
 main.cpp
 Proxy.cpp
""")

headers = Split("""
 Proxy.h
""")

proxy = env.Program('proxy', sources)
env.Default(proxy)

env['DOXYFILE_DICT'].update({ "PROJECT_NAME" : "Proxy" })
doxref = env.Apidocs(sources + headers)

SConscript("test/SConscript")

