#!/bin/sh

cp=(lib/*.jar )
OLDIFS=$IFS
IFS=:
# This syntax for expanding an array expands to a single word
# with each member separated by the first character in IFS
CLASSPATH="${cp[*]}"
IFS=$OLDIFS

echo $CLASSPATH
export CLASSPATH


[ -d classes ] || mkdir classes

javac -d classes  \
    ../src/edu/ucar/eol/nc2asc/*.java \
    ../src/edu/ucar/eol/nc2ascData/*.java \

jar cvfm nc2asc.jar manifest.txt -C classes .

