#! /bin/sh


### make nc2asc jar file
rm  nc2asc.jar
rm  javazip/*.zip 
svn revert lib/netcdfUI-2.2.22.jar  lib/nlog4j-1.2.25.jar  lib/commons-logging-1.1.jar  

source makejar


### sign keys
jarsigner -keystore javazip/nc2asc.keystore nc2asc.jar n2a
jarsigner -keystore javazip/nc2asc.keystore lib/netcdfUI-2.2.22.jar n2a
jarsigner -keystore javazip/nc2asc.keystore lib/nlog4j-1.2.25.jar  n2a
jarsigner -keystore javazip/nc2asc.keystore lib/commons-logging-1.1.jar n2a


### zip deployment files
cp ../doc/nc2asc.html doc/.
zip nc2asc.zip nc2asc.jar lib/netcdfUI-2.2.22.jar lib/nlog4j-1.2.25.jar lib/commons-logging-1.1.jar  doc/nc2asc.html doc/temp.batch
mv  nc2asc.zip javazip/.

cp javazip/nc2asc.jnlp .
zip nc2asc-ws.zip nc2asc.jar nc2asc.jnlp lib/netcdfUI-2.2.22.jar  lib/nlog4j-1.2.25.jar  lib/commons-logging-1.1.jar  doc/nc2asc.html  doc/temp.batch
mv  nc2asc-ws.zip javazip/.
rm  nc2asc.jnlp


### cleanup svn 
svn revert lib/netcdfUI-2.2.22.jar  lib/nlog4j-1.2.25.jar  lib/commons-logging-1.1.jar
