#!/bin/sh

source classpath.sh

[ -d classes ] || mkdir classes

javac -d classes  \
    ../src/edu/ucar/eol/nc2asc/*.java \
    ../src/edu/ucar/eol/nc2ascData/*.java \

jar cvfm nc2asc.jar manifest.txt -C classes .

